### ISSUE TITLE
Running a Single Image file To predict output

### ISSUE THREAD

**Issue by sarvesh211999** [torralba-lab/im2recipe-Pytorch#10]
Can anyboy help how to provide a single image file to the model and get the output ?

**Comment by nhynes** [comment]
Try loading up a pretrained model and then take the resnet out using

```python
vision_mlp = torch.load('path/to/pretrained.pth').visionMLP
resnet = resnet50(pretrained=True)
img = torch.tensor(1, 3, 224, 224)
out = vision_mlp(resnet(img))
```

**Comment by sarvesh211999** [comment]
The given code is incorrect since torch tensor take 1 positional arguments

**Comment by nhynes** [comment]
sorry that was the syntax for the newest version of pytorch

**Comment by sarvesh211999** [comment]
Any other idea
