### ISSUE TITLE
Very confused about the test.py

### ISSUE THREAD

**Issue by xiaoleihuang** [torralba-lab/im2recipe-Pytorch#19]
I tried the following code:
`python test.py --model_path=model/model_e220_v-4.700.pth.tar --img_path=./data/Tomato-and-egg-stir-fry-ingredients.jpg --data_path=./data/`, but it turns out the following error:

```
    print(..., file=sys.stderr)
          ^
SyntaxError: invalid syntax
```
What is the right way to load data?
What if I would like to test a single image or a group of images?

**Comment by jmarintur** [comment]
Hi @xiaoleihuang The code as it is, unless you build a new dataset with it (i.e. test_lmdb + test_keys.pkl), it is not meant to work like this. If you simply want to get the embedding output of an image, you can isolate the vision branch and run it manually.

**Comment by eatcosmos** [comment]
> Hi @xiaoleihuang The code as it is, unless you build a new dataset with it (i.e. test_lmdb + test_keys.pkl), it is not meant to work like this. If you simply want to get the embedding output of an image, you can isolate the vision branch and run it manually.

you can isolate the vision branch and run it manually
Hi @jmarintur what do you mean vision branch, i just find master and development in github of this repo.

**Comment by jmarintur** [comment]
My bad, I meant the "branch" within the network model, named visual_embedding. I've just uploaded a new script, image2embedding.py. You only need to provide an image to it, and you'll get the corresponding embedding.
