### ISSUE TITLE
mk_dataset.py hasnot taken the images into lmdb

### ISSUE THREAD

**Issue by pansiyuan123** [torralba-lab/im2recipe-Pytorch#22]
erialized_sample = pickle.dumps( {'ingrs':ingr_vec, 'intrs':st_vecs[partition]['encs'][beg:end],
        'classes':class_dict[entry['id']]+1, 'imgs':imgs[:maxNumImgs]} ) 

    with env[partition].begin(write=True) as txn:
        txn.put('{}'.format(entry['id']), serialized_sample)

**Comment by jmarintur** [comment]
In our implementation we did not consider including them.
