### ISSUE TITLE
Licence for using the Code (incl. model)

### ISSUE THREAD

**Issue by JonasMedu** [torralba-lab/im2recipe-Pytorch#26]
Your project is of great interest to me and i am very excited to try Your models!

You list Your code under the MIT licence and link Your parameter set (the model) in the read.me.

To actually being able to use Your model/code for inference, one would also need the vocabulary: `vocab.bin` .

Am i correct in the assumption, that You *do not allow* inference of Your model in commercial use (as part of a back-end service) ?
Otherwise, leave me a comment (which of course would make me very happy).

**Comment by nhynes** [comment]
The model is also MIT: free as in freedom. I do hope it finds use in commercial and non-commercial applications :)

Also, let me know if you want help building a new model. I've been wanting to throw some of the shiny new NLP models at the problem, but haven't had a good enough reason to.

Good luck!
