### ISSUE TITLE
IndexError on attempt to run pertained model 

### ISSUE THREAD

**Issue by Hiyorimi** [torralba-lab/im2recipe-Pytorch#27]
Running
```bash
python test.py --model_path=snapshots/model_e500_v-8.950.pth.tar
```
results in 

```bash
  File "/home/q/Projects/im2recipe-Pytorch/trijoint.py", line 65, in __init__
    self.embs = nn.Embedding(vec.size(0), opts.ingrW2VDim, padding_idx=0) # not sure about the padding idx
  File "/home/q/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/sparse.py", line 98, in __init__
    self.reset_parameters()
  File "/home/q/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/sparse.py", line 109, in reset_parameters
    self.weight[self.padding_idx].fill_(0)
IndexError: index 0 is out of bounds for dimension 0 with size 0
```

I'm using python3.7 fresh conda environment. From other issues I get that I should not have encountered such error. What can you advise to do? Fix padding ?

**Comment by Hiyorimi** [comment]
Sovled

**Comment by NickRothbacher** [comment]
I'm getting this same issue, what did you do to resolve it?

**Comment by Hiyorimi** [comment]
> I'm getting this same issue, what did you do to resolve it?

I patched the embedding repo according to the readme.

**Comment by NickRothbacher** [comment]
> > I'm getting this same issue, what did you do to resolve it?
> 
> I patched the embedding repo according to the readme.

What changes/repo are you referring to? I changed the torchwordemb package as recommended in the readme to no effect

**Comment by revathyramanan** [comment]
I am facing the same issue. Can someone please help?

**Comment by jmarintur** [comment]
Follow the instructions and check that the path in opts.ingrW2V is pointing at the right file, vocab.bin.
