### ISSUE TITLE
food101_classes_renamed.txt

### ISSUE THREAD

**Issue by lironghua318** [torralba-lab/im2recipe-Pytorch#33]
Where can I download this file?

**Comment by nhynes** [comment]
Is it not available [here](http://im2recipe.csail.mit.edu/dataset)?

**Comment by lironghua318** [comment]
Downloads
README
Layers (381 MiB)
Ingredient detections (102 MiB)
Recipe1M images
training (94 GiB)
validation (21 GiB)
test (20 GiB)
Recipe1M+ images
0, 1, 2, 3, 4, 5, 6, 7, 8, 9, a, b, c, d, e, f (approx. 210 Gib each tar file)
Layer2+
layer2+.json (2.5 GiB)
Model training files
data.h5.gz (89 GiB, recipe1M)
vocab.bin.gz (33 MiB)
classes1M.pkl (26 MiB)
train.tar (24 GiB, recipe1M)
val.tar (5 GiB, recipe1M)
test.tar (5 GiB, recipe1M)
encs_train_1024.t7 (29 GiB)
encs_val_1024.t7 (6 GiB)
encs_test_1024.t7 (6 GiB)
remove1M.txt (133 KiB)
Recipes with nutritional information
recipes_with_nutritional_info.json (213 MiB)

**where?**

**Comment by nhynes** [comment]
[found them](https://github.com/torralba-lab/im2recipe/blob/master/pyscripts/food101_classes_renamed.txt). I wonder how they got all the way over there?

**Comment by rixscx** [comment]
how or where to get the dataset ?
