### ISSUE TITLE
Registration to access dataset results in error

### ISSUE THREAD

**Issue by magnum6actual** [torralba-lab/im2recipe-Pytorch#38]
Not really an issue with this repository, but I'm unable to register for access to the dataset.  Upon submitting the registration form at 

returns the following error:

> Django Material
> Server error
> 
> There's been an error. It's been reported to the site administrators via email and should be fixed shortly. Thanks for your patience.

Following the error, I'm unable to login with the account I tried to setup.

**Comment by yazdavar** [comment]
Still, I am experiencing the same issue.
Is there any other place that you can put the dataset until the website problem gets fixed?

**Comment by jangho2001us** [comment]
Me too... (Django error)
I sent email for the authors as represented in their paper, but I did not take the response and some email addresses are not found...

Can someone remind me what I should do next?

**Comment by yazdavar** [comment]
Hi... He replied me today
With the link to the dataset...

fofli@hbku.edu.qa

Contact him...

Best
Amir

On Wed, Jun 24, 2020 at 8:13 PM Jangho Lee <notifications@github.com> wrote:

> Me too... (Django error)
> I sent email for the authors as represented in their paper, but I did not
> take the response and some email addresses are not found...
>
> Can someone remind me what I should do next?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_torralba-2Dlab_im2recipe-2DPytorch_issues_38-23issuecomment-2D649155267&d=DwMCaQ&c=3buyMx9JlH1z22L_G5pM28wz_Ru6WjhVHwo-vpeS0Gk&r=HshYvqHUvaRESLmjnZopJUlD9xymhJRsdH1vzDYGTFo&m=HGbe35GY8XLwCYpmAjQ7447v2694ozSArw-Onblf-n4&s=4sYTQA2mkwxTRThOgW-y_9mY5O2ESv-AFdrbxcWc90c&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ADAHVN6IDCH572BCKTDO7JDRYKQBHANCNFSM4NP5GBYA&d=DwMCaQ&c=3buyMx9JlH1z22L_G5pM28wz_Ru6WjhVHwo-vpeS0Gk&r=HshYvqHUvaRESLmjnZopJUlD9xymhJRsdH1vzDYGTFo&m=HGbe35GY8XLwCYpmAjQ7447v2694ozSArw-Onblf-n4&s=DppyfdFR-yqRHqCeSXplgCCYR9UmgtsFSWLXM7hpWmo&e=>
> .
>
-- 
Amir Hossein Yazdavar
PhD Researcher at DaSe Lab <https://daselab.cs.ksu.edu/>, Kansas State
University <https://www.k-state.edu/>
WWW <http://yazdavar.space> Twitter <https://twitter.com/yazdavar>  LinkedIn
<https://www.linkedin.com/profile/preview?locale=en_US&trk=prof-0-sb-preview-primary-button>

**Comment by jmarintur** [comment]
We will try to change the way you access to the data asap. For the time being send me an email. Thanks!
