### ISSUE TITLE
DB Download link not working

### ISSUE THREAD

**Issue by xiaopi-ouo** [torralba-lab/im2recipe-Pytorch#40]
Dear authors,

I am trying to download your dataset "Recipe1M+ dataset" from the provided link:
http://im2recipe.csail.mit.edu/dataset/login/

When I tried to log in it mentioned the This account is inactive.

I have not received any email for confirming the registration.

I tried to create a new user with different emails but some errors raised, and now it says the account has been taken.

I would really appreciate it if you can kindly follow up and send me the dataset link.

Best,
Allen

**Comment by waqasilyas** [comment]
Same problem here, some help would be really appreciated.

**Comment by Josh1108** [comment]
Same. Could not download it. Seems like the mailing system they have used with Django is not working.

**Comment by RollingWang** [comment]
I have the same problem

**Comment by Limitlessun** [comment]
I have the same problem

**Comment by XiaoSanGit** [comment]
I have the same problem

**Comment by jeroneandrews** [comment]
Same problem here.

**Comment by yenicelik** [comment]
Just write an e-mail to the author, he responded to my inquiry within 2 days: jmarin@csail.mit.edu

**Comment by jmarintur** [comment]
As @yenicelik is saying, just send me an email.

**Comment by Chaoran-F** [comment]
is it fine? If I wrote an email to yusuf.

**Comment by jmarintur** [comment]
@Chaoran-F, please send the email to me, jmarin@csail.mit.edu

**Comment by Shahrose-Khan** [comment]
@jmarintur , I sent you access request for recipe1M dataset. can you help me with it?
