### ISSUE TITLE
Error installing torchwordemb

### ISSUE THREAD

**Issue by ebeth-chin** [torralba-lab/im2recipe-Pytorch#48]
I'm trying to test the pretrained model but got the following error: 

`Traceback (most recent call last):
  File "test.py", line 13, in <module>
    from trijoint import im2recipe
  File "/project/recipe1m/im2recipe-Pytorch/trijoint.py", line 9, in <module>
    import torchwordemb
ModuleNotFoundError: No module named 'torchwordemb'`

but then I get the error when doing `pip install torchwordemb` 

`    /project/conda_env/recipe1m/lib/python3.7/site-packages/torch/include/ATen/core/dispatch/Dispatcher.h: In member function ‘Return c10::Dispatcher::doCallUnboxed(const c10::Dispatc
hTable&, const c10::LeftRight<ska::flat_hash_map<c10::TensorTypeId, c10::KernelFunction> >&, Args ...) const [with Return = bool; Args = {}]’:
    /project/conda_env/recipe1m/lib/python3.7/site-packages/torch/include/ATen/core/dispatch/Dispatcher.h:191:1: warning: control reaches end of non-void function [-Wreturn-type]
     }
     ^`
    `error: command 'gcc' failed with exit status 1` 
    
    Has anyone had success running test.py and/or installing torchwordemb?

**Comment by Youkeep** [comment]
我也遇到了同样问题，请问是如何解决的
