### ISSUE TITLE
vocab size

### ISSUE THREAD

**Issue by jingjing1** [torralba-lab/im2recipe-Pytorch#5]
I have tried the testing code with the pre-trained model, however, it reports the error "runtimeError: While copying the parameter named ingRNN_.embs.weight, whose dimensions in the model are torch.Size([30566, 300]) and whose dimensions in the checkpoint are torch.Size([30167, 300])."

**Comment by nhynes** [comment]
Thanks for the bug report! Question: are you also using the pre-trained `vocab.bin` and have pre-processed it using [scripts/get_vocab.py`](https://github.com/torralba-lab/im2recipe-Pytorch/blob/master/scripts/get_vocab.py)?

**Comment by jingjing1** [comment]
Yes, I used the pre-trained vocab.bin which obtain by the command
"./word2vec -hs 1 -negative 0 -window 10 -cbow 0 -iter 10 -size 300 -binary
1 -min-count 10 -threads 20 -train tokenized_instructions_train.txt -output
vocab.bin". Could you please update the vocab.bin to githup?

2018-04-03 21:18 GMT+08:00 nhynes <notifications@github.com>:

**Comment by nhynes** [comment]
Please use the pre-trained vocab.bin available for [download](http://im2recipe.csail.mit.edu/dataset/download/).

**Comment by jingjing1** [comment]
It works now, thanks very much.
