### ISSUE TITLE
Pre-trained model can't not find test_lmdb

### ISSUE THREAD

**Issue by skaznowiecki** [torralba-lab/im2recipe-Pytorch#51]
## Description
I'm trying to run the pre trained model using the following command within docker: 
(I already configure the vocab.bin file)

```
python test.py --model_path=snapshots/model_e500_v-8.950.pth.tar
```
I got this error: 

```
lmdb.Error: data/test_lmdb: No such file or directory
```
I can't find this file either in the repository or in this page http://im2recipe.csail.mit.edu/dataset/download/

**Comment by jmarintur** [comment]
Hi @skaznowiecki , sorry for the late reply. The file you are looking for is included in the recipe1M dataset. Feel free to fill the form available in [Recipe1M Dataset](https://github.com/torralba-lab/im2recipe-Pytorch#recipe1m-and-recipe1m-datasets)
