### ISSUE TITLE
im2recipe-Pytorch issue

### ISSUE THREAD

**Issue by MatteMagnaldi** [torralba-lab/im2recipe-Pytorch#52]
I wanted to try to train your model using a new dataset. Following your instructions, I would like to launch the script "tokenize_instructions.py", which however requires the "det_ingrs.json" file. I can't figure out how you got that file, through a particular script or some other way? and if so, how can I get it for the new recipe dataset I would like to use.

The paper talks about a model " The initial ingredient name extraction task is solved by a bi-directional LSTM that performs logistic regression on each word in the ingredient text", but I couldn't find the code associated with this model, which I think could be the one used to then obtain the "det_ingrs.json" file, but i'm not sure.

If you could help me with these doubts I would be very grateful.

**Comment by jmarintur** [comment]
Hi @MatteMagnaldi , sorry for the late reply. The file you are looking for is included in the Recipe1M dataset. Feel free to fill the form to access the data.
