### ISSUE TITLE
Problem of running test.py

### ISSUE THREAD

**Issue by jingjing1** [torralba-lab/im2recipe-Pytorch#6]
It seems test.py will not extract recipe embedding features and image embedding features. The code is running for more than 4 hours, but nothing has been saved (still running). I have checked the test.py, it seems that no data fed into the model. I think there may be something wrong with the test function.
%----------------------------------------------------------------------
for i, (input, target) in enumerate(test_loader):
        input_var = list() 
        for j in range(len(input)):
            v = torch.autograd.Variable(input[j], volatile=True)
        target_var = list()
        for j in range(len(target)-2): # we do not consider the last two objects of the list
            target[j] = target[j]
            v = torch.autograd.Variable(target[j], volatile=True)
            target_var.append(v.cuda() if not opts.no_cuda else v)

        # compute output
output = model(input_var[0],input_var[1], input_var[2], input_var[3], input_var[4])
%---------------------------------------------------------------------------------------------------
From the code, input_var is not updated and keeps empty. Could you help me address this?

**Comment by jingjing1** [comment]
I have fixed the bugs in test.py. So the only problem now is the wrong test_lmdb. Could you please updated a new one thus I can download for testing as soon as possible.

**Comment by nhynes** [comment]
> please updated a new one

No guarantees (since I didn't write this code) but I'll give it a shot. Thanks for your patience!

**Comment by jingjing1** [comment]
Are you the co-author of this paper? Actually, I'm comparing with the model, and need to have R@1, R@5 and R@10 when testing data size is 5K and 10K. Also, I need to do case studies compared with my model.

**Comment by nhynes** [comment]
> Are you the co-author of this paper? 

Yes, but I wrote the original Lua Torch version--not this one.

I won't be able to recreate the LMDBs until late today or tomorrow, so if you need something sooner, my recommendation is to take the HDF5 test set and package it into an LMDB yourself.

**Comment by jingjing1** [comment]
Hi, nhynes, thanks very much. Please notify me if you finish updating the LMDB file (only test data).  I just checked the provided HDF5 file, it is too large and will take more than 1 day to download.

**Comment by jingjing1** [comment]
Hi, nhynes, 
thanks very much. It works now. In deed, the LMDB file does not contain images. So I need to give the path of testing images.

**Comment by BigBugGrow** [comment]
"I have fixed the bugs in test.py. So the only problem now is the wrong test_lmdb. Could you please updated a new one thus I can download for testing as soon as possible."

**Comment by BigBugGrow** [comment]
I think that a similar issue was encountered in #6 but was fixed by @jingjing1. Perhaps they'd be willing to share their fix as a PR?

**Comment by BigBugGrow** [comment]
I think that a similar issue was encountered in #6 but was fixed by @jingjing1. Perhaps they'd be willing to share their fix as a PR?

**Comment by BigBugGrow** [comment]
Hi,jingjing1,
could you be willing to share your fix in test.py?
thanks very much.

**Comment by jingjing1** [comment]
Hi, DongAn,

I need to find the revised test.py file, and will send you soon.



2018-06-04 11:33 GMT+08:00 DongAn <notifications@github.com>:

**Comment by BigBugGrow** [comment]
Thank you very much！

**Comment by jingjing1** [comment]
Dear DongAn,

Add "input_var.append(v.cuda() if not opts.no_cuda else v)" right after
line 96 in test.py. And then run the scripts: (data_path is the path of
test_lmdb)

python test.py --model_path=model_e220_v-4.700.pth.tar --data_path=./

2018-06-04 12:14 GMT+08:00 陈静静 <chenjingjing.tju@gmail.com>:

**Comment by jingjing1** [comment]
Dear DongAn,

Add "input_var.append(v.cuda() if not opts.no_cuda else v)" right after
line 96 in test.py. And then run the scripts: (data_path is the path of
test_lmdb)

python test.py --model_path=model_e220_v-4.700.pth.tar --data_path=./

2018-06-04 14:54 GMT+08:00 DongAn <notifications@github.com>:

**Comment by BigBugGrow** [comment]
Dear jingjing,
It works now,thank you very much！

**Comment by JohnnyQIU0311** [comment]
Hi, did anyone also encounter this problem when running test.py? I'm not sure if all my configuration is correct or not. I installed pytorch in a python2.7 virtualenv and the unzipped files of test.tar are in data directory. Any help would be appreciated!

(pytorch-conda) kk118@graphic08:im2recipe-Pytorch$ python test.py --model_path=snapshots/model_e220_v-4.700.pth.tar 
Traceback (most recent call last):
  File "test.py", line 176, in <module>
    main()
  File "test.py", line 30, in main
    model = im2recipe()
  File "/homes/kk118/im2recipe-Pytorch/trijoint.py", line 103, in __init__
    resnet = models.resnet50(pretrained=True)
  File "/vol/bitbucket/kk118/anaconda2/envs/pytorch-conda/lib/python2.7/site-packages/torchvision-0.2.1-py2.7.egg/torchvision/models/resnet.py", line 188, in resnet50
  File "/vol/bitbucket/kk118/anaconda2/envs/pytorch-conda/lib/python2.7/site-packages/torch/utils/model_zoo.py", line 66, in load_url
    return torch.load(cached_file, map_location=map_location)
  File "/vol/bitbucket/kk118/anaconda2/envs/pytorch-conda/lib/python2.7/site-packages/torch/serialization.py", line 303, in load
    return _load(f, map_location, pickle_module)
  File "/vol/bitbucket/kk118/anaconda2/envs/pytorch-conda/lib/python2.7/site-packages/torch/serialization.py", line 459, in _load
    magic_number = pickle_module.load(f)
cPickle.UnpicklingError: bad pickle data

**Comment by avijit2verma** [comment]
> Hi, nhynes,
> thanks very much. It works now. In deed, the LMDB file does not contain images. So I need to give the path of testing images.

Hi @jingjing1 
If by any chance you look at this, can you explain in a bit more detail what you did? If I understand correctly, you need the actual image files along with the test_lmdb to run testing, right?

**Comment by maxwellfrom** [comment]
> Hi, did anyone also encounter this problem when running test.py? I'm not sure if all my configuration is correct or not. I installed pytorch in a python2.7 virtualenv and the unzipped files of test.tar are in data directory. Any help would be appreciated!
> 
> (pytorch-conda) kk118@graphic08:im2recipe-Pytorch$ python test.py --model_path=snapshots/model_e220_v-4.700.pth.tar
> Traceback (most recent call last):
> File "test.py", line 176, in
> main()
> File "test.py", line 30, in main
> model = im2recipe()
> File "/homes/kk118/im2recipe-Pytorch/trijoint.py", line 103, in **init**
> resnet = models.resnet50(pretrained=True)
> File "/vol/bitbucket/kk118/anaconda2/envs/pytorch-conda/lib/python2.7/site-packages/torchvision-0.2.1-py2.7.egg/torchvision/models/resnet.py", line 188, in resnet50
> File "/vol/bitbucket/kk118/anaconda2/envs/pytorch-conda/lib/python2.7/site-packages/torch/utils/model_zoo.py", line 66, in load_url
> return torch.load(cached_file, map_location=map_location)
> File "/vol/bitbucket/kk118/anaconda2/envs/pytorch-conda/lib/python2.7/site-packages/torch/serialization.py", line 303, in load
> return _load(f, map_location, pickle_module)
> File "/vol/bitbucket/kk118/anaconda2/envs/pytorch-conda/lib/python2.7/site-packages/torch/serialization.py", line 459, in _load
> magic_number = pickle_module.load(f)
> cPickle.UnpicklingError: bad pickle data

Hi @JohnnyQIU0311 ,
 I met the same problem, and I have solved it. I download the pre-trained model failed first time because of my limited disk space, when I run the second time, I met the problem, I solved it by deleting the incomplete model I download first and then the problem was solved. Hope it is helpful.
