### ISSUE TITLE
test.py didn't run

### ISSUE THREAD

**Issue by tomoki-oke** [torralba-lab/im2recipe-Pytorch#7]
I ran this command, then the below error occurred.
I suppose a reason why this error occurred, 
input_var array is initialized, but not appended value in test function.
-- Command
```
python test.py --model_path=snapshots/model_e220_v-4.700.pth.tar
```
-- Error
```
Traceback (most recent call last):
  File "test.py", line 176, in <module>
    main()
  File "test.py", line 80, in main
...
    test(test_loader, model, criterion)
  File "test.py", line 104, in test
    output = model(input_var[0],input_var[1], input_var[2], input_var[3], input_var[4])
```

**Comment by nhynes** [comment]
I think that a similar issue was encountered in #6 but was fixed by @jingjing1. Perhaps they'd be willing to share their fix as a PR?

**Comment by tomoki-oke** [comment]
I overlooked that issue. That's good to know.
